destination: &ops_ns labs-cluster-ops

##############
# üêô Argo Sync Policy
#############
sync_policy_true: &sync_policy_true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true

sync_policy_no_selfheal: &sync_policy_no_selfheal
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - Validate=true

applications:
  # Prune OpenShift Builds
  - name: prune-builds
    enabled: true
    source: https://github.com/redhat-cop/openshift-management.git
    source_path: charts/cronjob-prune-builds-deployments/
    sync_policy: *sync_policy_true
    destination: *ops_ns
    source_ref: "master"
    values:
      namespace: *ops_ns
      prune_type: builds
  # Prune OpenShift Deployments
  - name: prune-deployments
    enabled: true
    source: https://github.com/redhat-cop/openshift-management.git
    source_path: charts/cronjob-prune-builds-deployments/
    sync_policy: *sync_policy_true
    destination: *ops_ns
    source_ref: "master"
    values:
      namespace: *ops_ns
      prune_type: deployments
  # Container Security
  - name: container-security-operator
    enabled: true
    destination: openshift-operators
    source: https://github.com/rht-labs/refactored-adventure.git
    source_path: container-security-operator/base
    source_ref: master
    sync_policy: *sync_policy_true
    no_helm: true
  # User Workload Monitoring
  - name: user-workload-monitoring
    enabled: true
    destination: openshift-monitoring
    source: https://github.com/rht-labs/refactored-adventure.git
    source_path: user-workload-monitoring/base
    source_ref: master
    sync_policy: *sync_policy_true
    no_helm: true
  # Pet Battle Alerting
  - name: petbattle-alerts-dev
    destination: labs-dev
    enabled: true
    source: https://github.com/petbattle/ubiquitous-journey.git
    source_path: applications/alerting/chart
    sync_policy: *sync_policy_true
    source_ref: main
    values:
      petbattle:
        rules:
          severity: info
  - name: petbattle-alerts-test
    destination: labs-test
    enabled: true
    source: https://github.com/petbattle/ubiquitous-journey.git
    source_path: applications/alerting/chart
    sync_policy: *sync_policy_true
    source_ref: main
    values:
      petbattle:
        rules:
          severity: warning
  - name: petbattle-alerts-staging
    destination: labs-staging
    enabled: true
    source: https://github.com/petbattle/ubiquitous-journey.git
    source_path: applications/alerting/chart
    sync_policy: *sync_policy_true
    source_ref: main
    values:
      petbattle:
        rules:
          severity: warning
